vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        galerie:
            uri_prefix: /images/galerie
            upload_destination: '%kernel.project_dir%/public/images/galerie'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
